name: Check sitemap

on:
  workflow_dispatch:
    inputs:
      sitemap:
        type: string
        description: XML sitemap URL
        required: true

concurrency:
  group: check-sitemap-${{ inputs.sitemap }}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - uses: snok/install-poetry@v1
      - name: Install Poetry dependencies
        run: poetry install --no-interaction --no-root
      - name: Run link checker
        run: poetry run python app/link-checker.py ${{ inputs.sitemap }}
        continue-on-error: true
      - name: Archive report
        uses: actions/upload-artifact@v4
        with:
          name: link-report
          path: report.json

  check2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - uses: snok/install-poetry@v1
      - name: Install Poetry dependencies
        run: poetry install --no-interaction --no-root
      - name: Run link checker
        run: |
          poetry run python app/generate-pages-list.py ${{ inputs.sitemap }}
          poetry run linkchecker --check-extern pages.txt
