name: Check sitemap

on:
  workflow_dispatch:
    inputs:
      sitemap:
        type: string
        description: XML sitemap URL
        required: true

concurrency:
  group: check-sitemap-${{ inputs.sitemap }}

jobs:
  check1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - uses: snok/install-poetry@v1
      - name: Install Poetry dependencies
        run: poetry install --no-interaction --no-root
      - name: Run link checker
        run: poetry run python app/sitemap-link-checker.py ${{ inputs.sitemap }}
      - name: Archive report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report-1
          path: report.json

  check2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - uses: snok/install-poetry@v1
      - name: Install Poetry dependencies
        run: poetry install --no-interaction --no-root
      - name: Run link checker
        run: |
          poetry run python app/generate-sitemap-links-list.py ${{ inputs.sitemap }}
          poetry run linkchecker --check-extern --no-warnings --file-output=html --recursion-level=1 --no-robots links.txt
      - name: Archive report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report-2
          path: linkchecker-out.html
